version: '3'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    command: >
      bash -c '
      echo "Checking CA...";
        if [[ ! -f  /certs/ca.zip ]]; then
          echo "CA not found. Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out /certs/ca.zip;
          unzip -o /certs/ca.zip -d /certs;
        fi;
        echo "CA OK"

        echo "Checking certificates"
        if [[ ! -f /certs/es01.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem\
            --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key\
            --in config/certificates/instances.yml --out /certs/es01.zip;
          unzip /certs/es01.zip -d /certs;
        else
          echo "Certificates already present";
          ls $CERTS_DIR/certs;
        fi;
        echo "Certificates OK"

        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']

volumes: {"certs"}